version: '2'

services:
  api:
    build: ./api
    ports:
      - "80:80"
    volumes:
      - ./api:/app
    env_file:
      - api.env
    depends_on:
      - db
    tty: true
    command: "/bin/bash"

  db:
    build: ./db
    ports:
      - "5432:5432"
    env_file:
      - db.env
